"""initial

Revision ID: 20abe365054b
Revises: 
Create Date: 2026-05-15 12:59:53.227959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20abe365054b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aperturas_caja_fecha'), table_name='aperturas_caja')
    op.alter_column('cierres_diarios', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('cierres_diarios', 'ventas_reales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'ventas_oro',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'compras_reales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'gastos_reales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'oro_recolectado',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'reales_esperados',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'oro_esperado',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'reales_contados',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'oro_contado',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'diferencia_reales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'diferencia_oro',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'retiro_dueno_reales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'retiro_dueno_oro',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'se_deja_reales',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'se_deja_oro',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_cierres_diarios_fecha_op'), table_name='cierres_diarios')
    op.create_index(op.f('ix_cierres_diarios_fecha_operativa'), 'cierres_diarios', ['fecha_operativa'], unique=False)
    op.create_index(op.f('ix_cierres_diarios_id'), 'cierres_diarios', ['id'], unique=False)
    op.create_unique_constraint('uq_cierre_fecha_operativa', 'cierres_diarios', ['fecha_operativa'])
    op.drop_index(op.f('ix_distrib_venta'), table_name='distribuciones_fondos')
    op.drop_index(op.f('ix_fundiciones_lote'), table_name='fundiciones')
    op.drop_index(op.f('ix_pagos_venta_venta'), table_name='pagos_venta')
    op.drop_index(op.f('ix_transacciones_modulo'), table_name='transacciones')
    op.alter_column('ventas', 'monto_pagado',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ventas', 'saldo_pendiente',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_ventas_pieza_fund'), table_name='ventas_pieza')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ventas_pieza_fund'), 'ventas_pieza', ['fundicion_id'], unique=False)
    op.alter_column('ventas', 'saldo_pendiente',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ventas', 'monto_pagado',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_transacciones_modulo'), 'transacciones', ['modulo_origen'], unique=False)
    op.create_index(op.f('ix_pagos_venta_venta'), 'pagos_venta', ['venta_id'], unique=False)
    op.create_index(op.f('ix_fundiciones_lote'), 'fundiciones', ['lote_oro_id'], unique=False)
    op.create_index(op.f('ix_distrib_venta'), 'distribuciones_fondos', ['venta_pieza_id'], unique=False)
    op.drop_constraint('uq_cierre_fecha_operativa', 'cierres_diarios', type_='unique')
    op.drop_index(op.f('ix_cierres_diarios_id'), table_name='cierres_diarios')
    op.drop_index(op.f('ix_cierres_diarios_fecha_operativa'), table_name='cierres_diarios')
    op.create_index(op.f('ix_cierres_diarios_fecha_op'), 'cierres_diarios', ['fecha_operativa'], unique=False)
    op.alter_column('cierres_diarios', 'se_deja_oro',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'se_deja_reales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'retiro_dueno_oro',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'retiro_dueno_reales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cierres_diarios', 'diferencia_oro',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'diferencia_reales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'oro_contado',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'reales_contados',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'oro_esperado',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'reales_esperados',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'oro_recolectado',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'gastos_reales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'compras_reales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'ventas_oro',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'ventas_reales',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cierres_diarios', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('ix_aperturas_caja_fecha'), 'aperturas_caja', ['fecha_operativa'], unique=False)
    # ### end Alembic commands ###
